//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesM
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public int Id { get; set; }
        public string CustomerName { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public Nullable<int> DiscountId { get; set; }
        public string Info { get; set; }
        public bool HasDiscount { get; set; }
        public byte[] Banner { get; set; }
    }
}
