//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesM
{
    using System;
    using System.Collections.Generic;
    
    public partial class statistic
    {
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public Nullable<int> CPosition { get; set; }
        public Nullable<int> CClickedCount { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
    }
}
