//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesM
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int UserId { get; set; }
        public string LoginName { get; set; }
        public string Password { get; set; }
        public Nullable<int> UserDiscount { get; set; }
        public bool IsLoggedOn { get; set; }
        public bool IsAlive { get; set; }
        public Nullable<System.DateTime> LastAccessDate { get; set; }
        public int SessionExpTime { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public Nullable<int> Age { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public byte Avatar { get; set; }
        public int Favorites { get; set; }
        public string DeviceOS { get; set; }
    }
}
